homework20
FE38-Front-End/DashaNalivayko pull request #10
Opened 2020-12-12 18:35 UTC by dashanalivayko

посмотри очень тщательно, косяков быть не должно)

2020-12-24 11:26 UTC, akhovbok requested changes

2020-12-24 11:26 UTC, akhovbok commented on lesson20/app.js
> +function disabled () {
disabled не подходящее название для метода

2020-12-24 11:26 UTC, akhovbok commented on lesson20/app.js
> +    navLeft.classList.remove('disabled');
а вот массив кнопок обрабатывать удобнее, чем каждую кнопку отдельно

2020-12-24 11:26 UTC, akhovbok commented on lesson20/app.js
> +navLeft.addEventListener('click', () => {
а почему вы так сопротивляетесь event delegation

2020-12-24 11:26 UTC, akhovbok commented on lesson20/style.css
> +body {
со стилями видно что старалась)

2020-12-24 11:26 UTC, akhovbok commented on lesson20/index.html
> +            <button class="reset">RESET</button>
трансформацию текста обычно делают через стили

2020-12-24 14:46 UTC, dashanalivayko commented on lesson20/app.js
> +    navLeft.classList.remove('disabled');
исправила, но не понимаю, почему navigation[i] undefined

2020-12-27 12:28 UTC, dashanalivayko commented on lesson20/app.js
> +navLeft.addEventListener('click', () => {
Делегирование сделаю уже на калькуляторе, тут все равно мало кнопочек и т.к. на каждую кнопку много проверок и условий, то так лучше читается

2021-01-24 21:30 UTC, merged