Feature/lesson18
FE38-Front-End/DashaNalivayko pull request #6
Opened 2020-12-01 16:23 UTC by dashanalivayko

2020-12-03 12:12 UTC, akhovbok requested changes

2020-12-03 12:12 UTC, akhovbok commented on lesson18 (DOM)/app.js
> +const list = document.insertAdjacentHTML ('beforeend', '<ul id='ul'> Номера: </ul>');
`${}`

2020-12-03 12:12 UTC, akhovbok commented on lesson18 (DOM)/app.js
> +let elements = document.querySelectorAll ('li');
const

2020-12-04 20:48 UTC, dashanalivayko commented
Исправила все, одобри, пожалуйста)

2020-12-07 10:12 UTC, merged